### ISSUE TITLE
Save original Game string

### ISSUE THREAD

**Issue by igoralmeida** [hwiechers/chess_pgn_parser#2]
Hi and thanks for the crate!

I decided to write a chess-database-searcher-thingy to teach myself Rust, and I have been using your crate for the initial import of games from a PGN file.
Filtering and basic stuff like counting games with specific openings for example worked fine, but when trying to print back one (or several) game(s) I found that the original string is not (easily) available, and this means I would have to recreate the PGN string from `Game.moves` (itself a `Vec<GameMove>`), which looks quite painful.

I then focused on exporting a slice of the content string as another field in the `Game` struct, so I looked at [`game`](https://github.com/hwiechers/chess_pgn_parser/blob/master/src/lib.rs#L260) and peggler's [`rule`](https://docs.rs/peggler/0.1.0/src/peggler/lib.rs.html#21-27), with no obvious solution to a Rust newbie like myself.

Any thoughts / is there a better way?

Best regards

**Comment by hwiechers** [comment]
The parser functions take a string slice and return at tuple with of parsed data and a string slice representing the unparsed remainder of the input. You can determine what part of the input was parsed by comparing the lengths of the input and remainder slices. I've added a [branch] (https://github.com/hwiechers/chess_pgn_parser/tree/original_string) with a new function called, read_games_2, that does this.

I can't think of an easy way to get this inside the rule itself.

**Comment by igoralmeida** [comment]
Thanks, I'm using the branch now and it works fine. Do you intend to publish this on crates.io?

**Comment by hwiechers** [comment]
Yes, but I need to think of a better name for `read_games_2` and there is also a [licensing issue](https://github.com/hwiechers/chess_pgn_parser/issues/1) I want to resolve before I publish again.
